//정상 데이터 + (이미지 파일은 VSCODE로 추가 못함. 나중에 Postman으로 테스트할 예정)

//지금 테스트는 multipart/form-data 로 진행할 수 없기에 application/json로 대체함.
// -> 훗날 Postman으로 테스트할 경우엔 multipart/form-data로 진행하기



POST http://localhost:3000/api/register
Content-Type: application/json

{
    "userNum":"60222143",
	"name": "정유찬",
	"password": "1234",
    "nickname":"정그리우스",
	"email":"yuchan8003@naver.com",
	"category": ["우히히","몰라레후"]
}

###

POST http://localhost:3000/api/login
Content-Type: :application/json

{
	"userNum" : "60222143",
	"password" : "1234"
}

###

POST http://localhost:3000/api/login
Content-Type: :application/json

{
	"userNum" : "602221111",
	"password" : "ddddd"
}

###

POST http://localhost:3000/api/login
Content-Type: :application/json

{
	"userNum" : "60222143",
	"password" : "1234"
}

###

//정상 데이터 2
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "userNum":"60222146",
	"name": "김예린",
	"password": "1234",
    "nickname":"yyyy",
	"email":"yyyy@naver.com",
	"category": ["안녕","반가워"]
}

###
//필수 데이터가 빠진 경우 (ERROR)

POST http://localhost:3000/api/register
Content-Type: application/json

{
	"name": "홍길동",
	"password": "1234",
    "nickname":"HONG",
	"category": ["동길홍","홍길동"]
}

###

//학번이 겹친 경우

POST http://localhost:3000/api/register
Content-Type: application/json

{
    "userNum":"60222143",
	"name": "홍길동",
	"password": "1234",
    "nickname":"HONG",
    "email":"yuchan8003@naver.com",
	"category": ["동길홍","홍길동"]
}

###
//이메일이 겹치는 경우

POST http://localhost:3000/api/register
Content-Type: application/json

{
    "userNum":"60222141",
	"name": "홍길동",
	"password": "1234",
    "nickname":"HONG",
    "email":"yuchan8003@naver.com",
	"category": ["동길홍","홍길동"]
}

### 

//로그인 테스트 시작------------
POST http://localhost:3000/api/login
Content-Type:application/json

{
	"userNum":"60222143",
	"password":"1234"
}

### 

POST http://localhost:3000/api/login
Content-Type:application/json

{
	"userNum":"60222159",
	"password":"1234"
}


###

POST http://localhost:3000/api/login
Content-Type:application/json

{
	"userNum":"60221111",
	"password":"1234"
}


### 

POST http://localhost:3000/api/login
Content-Type:application/json

{
	"userNum":"6199",
	"password":"14"
}

###

POST http://localhost:3000/api/login
Content-Type:application/json

{
	"userNum":"60222222",
	"password":"12345"
}

###

POST http://localhost:3000/api/login
Content-Type:application/json

{
	"userNum":"60222227",
	"password":"12345"
}

###

POST http://localhost:3000/api/login
Content-Type:application/json

{
	"userNum":"60222143",
	"password":"1234"
}

//로그인 테스트 끝------------

###

//Bearer <Token> 방식
GET http://localhost:3000/api/user_page
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwidXNlck51bSI6NjAyMjIxNDMsImlhdCI6MTczMTY2NjgxNywiZXhwIjoxNzMxNjcwNDE3fQ.doQnkaq1SfLMT2LNwRpStboAaX4pmqU6kucVwD0SxOA

###

GET http://localhost:3000/api/user_page
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlck51bSI6IjYyM2JhYzU0MjI4ZTY0MTEwNWQzMjIwMWVmZjM2YWE5YTBmOTYyODA3OWI3Yjc4MjhjMDE5M2FiYjUyODc4NTciLCJpYXQiOjE3MzIxMjc3ODgsImV4cCI6MTczMjEzMTM4OH0.ZqCE68irO2ItGO3Bf1wv_h3RIKmuD4A-GoceVVIE_rY

###

DELETE http://localhost:3000/api/user_page
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwidXNlck51bSI6NjAyMjIyMjIsImlhdCI6MTczMTE1MDk1NCwiZXhwIjoxNzMxMTU0NTU0fQ.4WUPO4j8-MSFXY2U9M-d-s4gXyfn2jEZ_lCGPmiIIt0

{
	"password" :"1234"
}

###

DELETE http://localhost:3000/api/user_page
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwidXNlck51bSI6NjAyMjIyMjIsImlhdCI6MTczMTE1MDk1NCwiZXhwIjoxNzMxMTU0NTU0fQ.4WUPO4j8-MSFXY2U9M-d-s4gXyfn2jEZ_lCGPmiIIt0

{
	"password" :"12345"
}

###

GET http://localhost:3000/api/group/8
Content-Type: application/json

###

DELETE http://localhost:3000/api/group/11
Content-Type: application/json

###

POST http://localhost:3000/api/login
Content-Type:application/json

{
	"userNum":"60222154",
	"password":"1234"
}
